
name: sigstore signing workflow


on:
  push:
    tags:
      - '*'     

permissions:
  contents: write
  id-token: write

jobs:
  sign-with-sigstore:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sign artifact with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./file.txt
          release-signing-artifacts: true
          upload-signing-artifacts: true
