
name: Release Workflow

on:
  push:
     tags:
       - '*'     
permissions:
    contents: write
    id-token: write

jobs:
    helm-release:
      runs-on: ubuntu-latest
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v2
     
        - name: Create release
          uses: softprops/action-gh-release@v1
          with:
            body_path: ${{ github.workspace }}/CHANGELOG.md
            tag_name: ${{ github.ref.tag_name}}  
            name: ${{ github.ref.tag_name}}
            draft: false
            prerelease: false
            token: ${{ secrets.GITHUB_TOKEN }}


        - uses: sigstore/gh-action-sigstore-python@v3.0.0  
          with:
              inputs: ./file.txt
              internal-be-careful-debug: true
              release-signing-artifacts: true
              verify-cert-identity: empty
              verify-oidc-issuer: empty      