
name: Release Workflow


on:
  push:
    tags:
      - '*'     

permissions:
  contents: write
  id-token: write

jobs:
  helm-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Sign artifact with Sigstore
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./file.txt
          release-signing-artifacts: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./file.txt
          body_path: ${{ github.workspace }}/CHANGELOG.md
          tag_name: ${{ github.ref_name }}  # Utilisation correcte pour récupérer le tag
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Correction pour utiliser le GITHUB_TOKEN



                  