name: Sign with Sigstore action

on:
    push:
        branches:
        - master
permissions:
    contents: write                         
    id-token: write                       
jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: ./file.txt
        verify: false
        release-signing-artifacts: true
        # verify-cert-identity: empty #Empty par défaut
        # verify-oidc-issuer: empty #https://oauth2.sigstage.dev/auth #Empty par défaut