name: Sign with Sigstore action

on:
    push:
        branches:
        - main

jobs:
  sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: sigstore/gh-action-sigstore-python@v3.0.0
      with:
        inputs: ./file.txt
        verify: true # ou false par défaut
        verify-cert-identity: john.hancock@example.co #Empty par défaut
        verify-oidc-issuer: https://oauth2.sigstage.dev/auth #Empty par défaut